# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'About',   url: 'about'}
- {name: 'Venues',  url: 'venues'}
- {name: 'Contact', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook',  link:   'https://www.facebook.com'}
- {icon: 'discord',   link: 'https://discord.com'}
- {icon: 'envelope',  link:   'mailto:westcountryleders@gmail.com'}

# Customize site text
# pagination:
#   next_page: 'Newer'
#   previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
